<?php

namespace Intercom\Types;

use Intercom\Core\Json\JsonSerializableType;
use Intercom\Core\Json\JsonProperty;

/**
 * The object who initiated the conversation, which can be a Contact, Admin or Team. Bots and campaigns send messages on behalf of Admins or Teams. For Twitter, this will be blank.
 */
class ConversationPartAuthor extends JsonSerializableType
{
    /**
     * @var ?string $type The type of the author
     */
    #[JsonProperty('type')]
    private ?string $type;

    /**
     * @var ?string $id The id of the author
     */
    #[JsonProperty('id')]
    private ?string $id;

    /**
     * @var ?string $name The name of the author
     */
    #[JsonProperty('name')]
    private ?string $name;

    /**
     * @var ?string $email The email of the author
     */
    #[JsonProperty('email')]
    private ?string $email;

    /**
     * @var ?bool $fromAiAgent If this conversation part was sent by the AI Agent
     */
    #[JsonProperty('from_ai_agent')]
    private ?bool $fromAiAgent;

    /**
     * @var ?bool $isAiAnswer If this conversation part body was generated by the AI Agent
     */
    #[JsonProperty('is_ai_answer')]
    private ?bool $isAiAnswer;

    /**
     * @param array{
     *   type?: ?string,
     *   id?: ?string,
     *   name?: ?string,
     *   email?: ?string,
     *   fromAiAgent?: ?bool,
     *   isAiAnswer?: ?bool,
     * } $values
     */
    public function __construct(
        array $values = [],
    ) {
        $this->type = $values['type'] ?? null;
        $this->id = $values['id'] ?? null;
        $this->name = $values['name'] ?? null;
        $this->email = $values['email'] ?? null;
        $this->fromAiAgent = $values['fromAiAgent'] ?? null;
        $this->isAiAnswer = $values['isAiAnswer'] ?? null;
    }

    /**
     * @return ?string
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * @param ?string $value
     */
    public function setType(?string $value = null): self
    {
        $this->type = $value;
        return $this;
    }

    /**
     * @return ?string
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * @param ?string $value
     */
    public function setId(?string $value = null): self
    {
        $this->id = $value;
        return $this;
    }

    /**
     * @return ?string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param ?string $value
     */
    public function setName(?string $value = null): self
    {
        $this->name = $value;
        return $this;
    }

    /**
     * @return ?string
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param ?string $value
     */
    public function setEmail(?string $value = null): self
    {
        $this->email = $value;
        return $this;
    }

    /**
     * @return ?bool
     */
    public function getFromAiAgent(): ?bool
    {
        return $this->fromAiAgent;
    }

    /**
     * @param ?bool $value
     */
    public function setFromAiAgent(?bool $value = null): self
    {
        $this->fromAiAgent = $value;
        return $this;
    }

    /**
     * @return ?bool
     */
    public function getIsAiAnswer(): ?bool
    {
        return $this->isAiAnswer;
    }

    /**
     * @param ?bool $value
     */
    public function setIsAiAnswer(?bool $value = null): self
    {
        $this->isAiAnswer = $value;
        return $this;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->toJson();
    }
}
